<?php

include_once('nossasp_organization.features.inc');

function nossasp_organization_views_pre_view(&$view) {
  if ($view->name == 'nossasp_organization_update_orgs') {
    $empty_text = 'Você ainda não cadastrou nenhuma organização.'. ' ' . l('Que tal começar agora?','node/add/nossasp-organization');
    $view->display_handler->set_option('empty', $empty_text);
  }
  elseif ($view->name == 'nossasp_organizations_map') { 
    if (drupal_is_front_page() &! (isset($_GET['circle']) || isset($_GET['title']))) {
      $view->display_handler->set_option('style_options', array('preset' => 'nossasp_all'));
    }
  }
}

function nossasp_organization_views_pre_render(&$view) {
  if ($view->name == 'nossasp_organizations_search_box') {
    $header_text = '<p class="counter"><span class="number">' . count($view->result)  . '</span> resultados</p>';
    $header_text .= '<p class="download">' . l('Baixe o banco de dados do mapa', 'organizations/data') . '</p>';
    $view->display_handler->set_option('header', $header_text);
  }
}

function nossasp_organization_perm() {
  return array('create municipal councils');
}

function nossasp_organization_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-nossasp-organizations-map-page-2') {
    $form['circle']['location']['#autocomplete_path'] = 'openlayers/geocoder/response';
    drupal_add_css(drupal_get_path('module','nossasp_organization') . '/nossasp-organization-search.css');
    $form['title']['#size'] = $form['circle']['location']['#size'] = 72;
    $form['tid']['#type'] = 'checkboxes';
    $form['#after_build'][] = 'nossasp_organization_exposed_search';
  }
  if ($form_id == 'nossasp_organization_node_form') {
    $form['field_tipo']['#title'] = $form['field_atuacao']['#title'] = FALSE;
    if (user_access('create municipal councils')) {
      drupal_add_js(drupal_get_path('module', 'nossasp_organization') . '/nossasp-organization-node-form.js');
    }
  }
}

function nossasp_organization_exposed_search($form, &$form_state) {

  $form['circle']['value']['#value'] = 5;
  $form['circle']['value']['#type'] = $form['circle_op']['#type'] = 'hidden';
  unset($form['circle']['location']['#field_prefix']);
  $form['circle']['min']['#access'] = $form['circle']['max']['#access'] = FALSE;
  $form['submit']['#weight'] = 0;

  return $form;
}

