<?php

include_once('nossasp_organization.features.inc');

function nossasp_organization_views_pre_render(&$view) {
  if ($view->name == 'nossasp_organization_update_orgs') {
    $empty_text= 'Você ainda não cadastrou nenhuma organização.'. ' ' . l('Que tal começar agora?','node/add/nossasp-organization');
    $view->display_handler->set_option('empty', $empty_text);
  }
}

function nossasp_organization_perm() {
  return array('create municipal councils');
}

function nossasp_organization_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'nossasp_organization_node_form') {
    $form['field_tipo']['#title'] = $form['field_atuacao']['#title'] = FALSE;
  }
}

