<?php

include_once('nossasp_contexts.features.inc');

function nossasp_contexts_context_registry() {
  return array(
    'conditions' => array(
      'nossasp_contexts_search_results' => array(
        'title' => t('Map search results'),
        'description' => t('Set the condition if the results of a map search are being shown'),
        'plugin' => 'nossasp_contexts_search_results_condition',
      ), 
    ), 
  ); 
}

function nossasp_contexts_context_plugins() {
  $plugins = array();
  $plugins['nossasp_contexts_search_results_condition'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'nossasp_contexts'),
      'file' => 'nossasp_contexts.context.conditions.inc',
      'class' => 'nossasp_contexts_search_results_condition',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

function nossasp_contexts_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'view' && in_array($node->type, array('nossasp_organization', 'nossasp_council')) && (isset($_GET['circle']) || isset($_GET['title']))) {
    if ($plugin = context_get_plugin('condition', 'nossasp_contexts_search_results')) {
      $plugin->execute();
    }
  }
}

function nossasp_contexts_init() {
  if (drupal_is_front_page() && (isset($_GET['circle']) || isset($_GET['title']))) {
    if ($plugin = context_get_plugin('condition', 'nossasp_contexts_search_results')) {
      $plugin->execute();
    }
  }
}

function nossasp_contexts_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => 'Cadastre sua organização',
    );
    return $blocks;
  }
  if ($op == 'view') {
    switch ($delta) {
      case 0:
        $block = array(
          'subject' => '',
          'content' => '<p>' . l('Cadastre sua organização', 'node/add/nossasp-organization') . '</p>',
        );
        break;
    }
    return $block;
  }
}
